//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.16 at 11:27:44 AM IST 
//


package com.soapConsumer.courseBeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soapConsumer.courseBeans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soapConsumer.courseBeans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCourseInfoRequest }
     * 
     */
    public GetCourseInfoRequest createGetCourseInfoRequest() {
        return new GetCourseInfoRequest();
    }

    /**
     * Create an instance of {@link GetCourseInfoResponse }
     * 
     */
    public GetCourseInfoResponse createGetCourseInfoResponse() {
        return new GetCourseInfoResponse();
    }

    /**
     * Create an instance of {@link CourseInfo }
     * 
     */
    public CourseInfo createCourseInfo() {
        return new CourseInfo();
    }

    /**
     * Create an instance of {@link GetAllCourseInfoRequest }
     * 
     */
    public GetAllCourseInfoRequest createGetAllCourseInfoRequest() {
        return new GetAllCourseInfoRequest();
    }

    /**
     * Create an instance of {@link GetAllCourseInfoResponse }
     * 
     */
    public GetAllCourseInfoResponse createGetAllCourseInfoResponse() {
        return new GetAllCourseInfoResponse();
    }

    /**
     * Create an instance of {@link DeleteCourseInfoRequest }
     * 
     */
    public DeleteCourseInfoRequest createDeleteCourseInfoRequest() {
        return new DeleteCourseInfoRequest();
    }

    /**
     * Create an instance of {@link DeleteCourseInfoResponse }
     * 
     */
    public DeleteCourseInfoResponse createDeleteCourseInfoResponse() {
        return new DeleteCourseInfoResponse();
    }

}
