//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 10:38:50 PM IST 
//


package com.soapConsumer.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseInfo" type="{http://www.soapConsumer.com/client}CourseInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseInfo"
})
@XmlRootElement(name = "GetCourseInfoResponse")
public class GetCourseInfoResponse{

    @XmlElement(name = "CourseInfo", required = true)
    protected CourseInfo courseInfo;

    /**
     * Gets the value of the courseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CourseInfo }
     *     
     */
    public CourseInfo getCourseInfo() {
        return courseInfo;
    }

    /**
     * Sets the value of the courseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseInfo }
     *     
     */
    public void setCourseInfo(CourseInfo value) {
        this.courseInfo = value;
    }

}
