//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 10:38:50 PM IST 
//


package com.soapConsumer.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soapconsumer.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SoapResponseGetCourseInfoResponse_QNAME = new QName("http://www.soapConsumer.com/client", "GetCourseInfoResponse");
    private final static QName _SoapResponseGetAllCourseInfoResponse_QNAME = new QName("http://www.soapConsumer.com/client", "GetAllCourseInfoResponse");
    private final static QName _SoapResponseDeleteCourseInfoResponse_QNAME = new QName("http://www.soapConsumer.com/client", "DeleteCourseInfoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soapconsumer.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SoapResponse }
     * 
     */
    public SoapResponse createSoapResponse() {
        return new SoapResponse();
    }

    /**
     * Create an instance of {@link DeleteCourseInfoResponse }
     * 
     */
    public DeleteCourseInfoResponse createDeleteCourseInfoResponse() {
        return new DeleteCourseInfoResponse();
    }

    /**
     * Create an instance of {@link SoapRequest }
     * 
     */
    public SoapRequest createSoapRequest() {
        return new SoapRequest();
    }

    /**
     * Create an instance of {@link GetAllCourseInfoResponse }
     * 
     */
    public GetAllCourseInfoResponse createGetAllCourseInfoResponse() {
        return new GetAllCourseInfoResponse();
    }

    /**
     * Create an instance of {@link CourseInfo }
     * 
     */
    public CourseInfo createCourseInfo() {
        return new CourseInfo();
    }

    /**
     * Create an instance of {@link GetCourseInfoResponse }
     * 
     */
    public GetCourseInfoResponse createGetCourseInfoResponse() {
        return new GetCourseInfoResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.soapConsumer.com/client", name = "GetCourseInfoResponse", scope = SoapResponse.class)
    public JAXBElement<Object> createSoapResponseGetCourseInfoResponse(Object value) {
        return new JAXBElement<Object>(_SoapResponseGetCourseInfoResponse_QNAME, Object.class, SoapResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.soapConsumer.com/client", name = "GetAllCourseInfoResponse", scope = SoapResponse.class)
    public JAXBElement<Object> createSoapResponseGetAllCourseInfoResponse(Object value) {
        return new JAXBElement<Object>(_SoapResponseGetAllCourseInfoResponse_QNAME, Object.class, SoapResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.soapConsumer.com/client", name = "DeleteCourseInfoResponse", scope = SoapResponse.class)
    public JAXBElement<Object> createSoapResponseDeleteCourseInfoResponse(Object value) {
        return new JAXBElement<Object>(_SoapResponseDeleteCourseInfoResponse_QNAME, Object.class, SoapResponse.class, value);
    }

}
