//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.04 at 10:38:50 PM IST 
//


package com.soapConsumer.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="GetCourseInfoResponse" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="GetAllCourseInfoResponse" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *           &lt;element name="DeleteCourseInfoResponse" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse"
})
@XmlRootElement(name = "soapResponse")
public class SoapResponse{

    @XmlElementRefs({
        @XmlElementRef(name = "DeleteCourseInfoResponse", namespace = "http://www.soapConsumer.com/client", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GetAllCourseInfoResponse", namespace = "http://www.soapConsumer.com/client", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GetCourseInfoResponse", namespace = "http://www.soapConsumer.com/client", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<Object>> getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse;

    /**
     * Gets the value of the getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getGetCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse() {
        if (getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse == null) {
            getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse = new ArrayList<JAXBElement<Object>>();
        }
        return this.getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse;
    }

	public void setGetCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse(
			List<JAXBElement<Object>> getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse) {
		this.getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse = getCourseInfoResponseOrGetAllCourseInfoResponseOrDeleteCourseInfoResponse;
	}

}
